# Generated by Django 5.2.8 on 2025-12-19 17:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arenas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='arena',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='court',
            options={'ordering': ['arena_id', 'name']},
        ),
        migrations.AddField(
            model_name='arena',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='court',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterUniqueTogether(
            name='court',
            unique_together={('arena', 'name')},
        ),
    ]
