# Generated by Django 5.2.8 on 2025-12-20 06:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arenas', '0002_alter_arena_options_alter_court_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SlotTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.PositiveSmallIntegerField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('base_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('court', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slot_templates', to='arenas.court')),
            ],
            options={
                'ordering': ['court_id', 'weekday', 'start_time'],
                'unique_together': {('court', 'weekday', 'start_time', 'end_time')},
            },
        ),
    ]
