# Generated by Django 5.2.8 on 2025-12-20 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arenas', '0003_slottemplate'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='slottemplate',
            constraint=models.CheckConstraint(condition=models.Q(('end_time__gt', models.F('start_time'))), name='slottemplate_end_after_start'),
        ),
    ]
